compile:
	javac -source 1.6 -target 1.6 -classpath /Library/tomcat/lib/servlet-api.jar:../lib/gdata-spreadsheet-3.0.jar:../lib/gdata-spreadsheet-meta-3.0.jar:../lib/guava-11.0.2.jar:../lib/jsr305.jar:../lib/mailapi.jar:../lib/gdata-core-1.0.jar edu/gsu/storygraph/*.java
run1:
	java edu.gsu.storygraph.AFGReader
run2:
	java edu.gsu.storygraph.BipartiteProcessor
