compile:
	javac -classpath /Library/tomcat/lib/servlet-api.jar:../lib/gson-2.2.4.jar:../lib/jsoup-1.8.3.jar edu/gsu/vis/*.java
compile_downgrade:
	javac -target 1.7 -source 1.7 -classpath /Library/tomcat/lib/servlet-api.jar:../lib/gson-2.2.4.jar:../lib/jsoup-1.8.3.jar edu/gsu/vis/*.java
